### ISSUE TITLE
eris-lavalink does not support Lavalink 2.x yet

### ISSUE THREAD

**Issue by InATrance** [briantanner/eris-lavalink#14]
As the title says, Lavalink 2.x got released and eris-lavalink doesn't support it yet.

Changes in 2.x: https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md#changes-v13---v20

**Comment by AnotherGenZ** [comment]
@InATrance eris-lavalink now supports Lavalink v2. Please refer to the README for installation.

**Comment by briantanner** [comment]
Now supports v2!
