### ISSUE TITLE
Player.paused is undefined? 

### ISSUE THREAD

**Issue by bjxke** [briantanner/eris-lavalink#15]
![image](https://user-images.githubusercontent.com/20141653/36215831-13b3c1ae-11a5-11e8-9e78-cf34f63c8626.png)

player.connection is the Player class, however paused seems to be always undefined?

**Comment by itslukej** [comment]
eris-lavalink only sets the value to `false` (https://github.com/briantanner/eris-lavalink/blob/master/src/Player.js#L50), the only way it could be undefined is when it is set like that: https://github.com/briantanner/eris-lavalink/blob/master/src/Player.js#L193

**Comment by bjxke** [comment]
I use setPause to use the opposite of weather it's already paused or not. But even without setting it, it's always undefined.
