### ISSUE TITLE
player.setPause() does nothing

### ISSUE THREAD

**Issue by PassTheMayo** [briantanner/eris-lavalink#16]
Hello. I just recently started using Lavalink, and I love it! I believe it's a great audio library, and it greatly decreased CPU usage. The only problem I have is when I try to use `player.setPause()`, it does nothing. No logs or errors, nothing. Here's my code: https://h.mayo.pw/ugogibamuv.js. I don't know what causes this, but it never works. Any help?

Note: This isn't my production code, I'm just messing around with Lavalink at the moment.

**Comment by briantanner** [comment]
You're not passing true or false...
`player.setPause(true);`
`player.setPause(false);`

**Comment by PassTheMayo** [comment]
@briantanner Oooooooh, I'm blind. Lmao
