### ISSUE TITLE
Error when running multiple player.play() after each other

### ISSUE THREAD

**Issue by PassTheMayo** [briantanner/eris-lavalink#17]
I am trying to run a music bot, and it works great for only one song. When I try to use `player.play(track)` after the previous song ended, it emits `end` earlier than expected. Let's say I make the bot play a song, then queue another song after that. It finishes the first song, then goes onto the second song. Halfway through the second song, the `player` suddenly emits `end` even though the audio wasn't finished playing. Here is a picture of what console looks like when I let the song finish, and close up, then I play another song and let it rejoin:
![image](https://user-images.githubusercontent.com/16949253/36823552-4ded2bca-1cc3-11e8-9224-654ba6783494.png)
This is what console looks like when I try to queue multiple songs after each other:
![image](https://user-images.githubusercontent.com/16949253/36823572-68d71f7c-1cc3-11e8-944e-9aa067e71554.png)
As you can see, it emits `end` twice before it even lets the second song end and the third song start. The reason it emits the error is because it called `end` before it let the other songs play, caused on my end of this. Here's my code: https://h.mayo.pw/exasojulos.js. I hope this helps, thanks!

**Comment by briantanner** [comment]
This is not a bug in the lib, you should handle possible race conditions as it works via websocket. Please read the documentation, check out the way Lavalink works, and how eris-lavalink communicates with it. While it can be easy, this isn't for beginners and is specifically geared towards public music bots which need the added performance benefit of distributed voice servers. If you don't need this, please consider using built-in eris voice/audio.

If you can find/verify a bug in eris-lavalink, please do submit an issue.

**Comment by PassTheMayo** [comment]
Last time I checked, there are no official Lavalink docs, just docs for the Eris Lavalink lib. Link? @briantanner

**Comment by auguwu** [comment]
@briantanner, I don't think there is any Lavalink-related documentation.

**Comment by briantanner** [comment]
https://github.com/Frederikam/Lavalink/blob/master/IMPLEMENTATION.md

**Comment by briantanner** [comment]
Because it works over websocket, you will have to manage the possibility of race conditions, set proper cooldowns in you commands, prevent people from being able to play two songs in rapid succession, these sorta things. This is pretty standard regardless of lib, bot, etc.

**Comment by PassTheMayo** [comment]
@briantanner So do I need to limit playing short songs rapidly, or prevent searching tracks quickly? Searching tracks seems to be working fine.

**Comment by PassTheMayo** [comment]
@briantanner That doesn't seem to be the case. As I see it, this is entirely a problem with `eris-lavalink`. I started debugging, and here's my log:
```
player.play() called
end event emitted
player.play() called
end event emitted
end event emitted
player.play() called
player.play() called
end event emitted
end event emitted
end event emitted
end event emitted
player.play() called
player.play() called
player.play() called
end event emitted
end event emitted
```
As you can see, the first 3 lines went fine, but then the player went haywire and started emitting `end` events like crazy. According to Lavalink, everything is all fine. I'm not sure what is up with this lib, but no one else is having this issue, and it's definitely not a rate limiting issue like you suggested.
